variable "env" {}
variable "component" {}
variable "instance_type" {}
variable "vpc_id" {}
variable "app_port" {}
variable "vpc_cidr" {}
variable "subnets" {}
variable "bastion_node_cidr" {}
variable "instance_count" {}
variable "prometheus_cidr" {}
variable "zone_id" {}
variable "listener_arn" {}
variable "alb_dns_name" {}
variable "listener_rule_priority" {}